EC_TOPIC = "+/sensors/ec"
FLOATER_TOPIC = "+/sensors/floater"
HUMIDITY_TOPIC = "+/sensors/humidity"
PH_TOPIC = "+/sensors/ph"
PUMP_NUTRIENT_TOPIC = "actuators/pumps/nutrient"
PUMP_PH_DOWN_TOPIC = "actuators/pumps/ph_down"
PUMP_PH_UP_TOPIC = "actuators/pumps/ph_up"
PUMP_WATER_TOPIC = "actuators/pumps/water"
ROOM_TEMP_TOPIC = "+/sensors/room_temperature"
TEMP_TOPIC = "+/sensors/temperature"
SWITCH_LIGHT_OFF_TOPIC = "actuators/light_off"
SWITCH_LIGHT_ON_TOPIC = "actuators/light_on"

TIMEZONE = "America/Buenos_Aires"
TIME_THRESHOLD = 5
