
# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

automation: !include automations.yaml
rest_command: !include rest_commands.yaml
template: !include templates.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
