TEMP_TOPIC = 'sensors/temperature'
PH_TOPIC = 'sensors/ph'
EC_TOPIC = 'sensors/ec'
PUMP_PH_UP_TOPIC = 'actuators/pumps/ph_up'
PUMP_PH_DOWN_TOPIC = 'actuators/pumps/ph_down'
PUMP_NUTRIENT_TOPIC = 'actuators/pumps/nutrient'
SWITCH_LIGHT_TOPIC = 'actuators/light'